# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a14b9115e3a0c4572a351b7a4bd0c51ec6cacef7e404c0727f717cd6bf15a1b27e86e3cb1919cda23f67a6695811c8b46323370588a06b00a1f3af9f2796d8ca

test:
  secret_key_base: d277177d06b776f55759de551ee8434cb72f8be1d3115b4aee535562ae69c4dc10069dae7031c4276ddc92cbb3cee4fcf82e54b18577b90c65aa62c1b59e7b61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
